// Generated by CoffeeScript 1.7.1
(function() {
  this.BezierCustomRun = (function() {
    function BezierCustomRun() {
      var points;
      this.bezierCanvas = $('#bezierCanvas');
      points = [];
      points.push({
        x: 10,
        y: 10
      });
      points.push({
        x: 20,
        y: 40
      });
      points.push({
        x: 30,
        y: 20
      });
      points.push({
        x: 40,
        y: 85
      });
      points.push({
        x: 50,
        y: 70
      });
      points.push({
        x: 60,
        y: 0
      });
      points.push({
        x: 70,
        y: 50
      });
      points.push({
        x: 80,
        y: 30
      });
      points.push({
        x: 85,
        y: 70
      });
      points.push({
        x: 100,
        y: 50
      });
      this.curve = new BezierCurve(points, this.bezierCanvas, 110, 100);
      this.curve.play();
    }

    return BezierCustomRun;

  })();

  $(function() {
    var bezier;
    return bezier = new BezierCustomRun();
  });

}).call(this);
